config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :donations

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :comments
end

app/models/user.rb
class User < ApplicationRecord
	has_many :donations
	has_many :comments
	has_secure_password
    validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	validates :password, :length => { :within => 6..40 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user.donations.build(params[:donations])
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'Conta criada com sucesso!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: "form form-signup") do |form| %>
  <h1 class="form-title-signup">Perfil</h1>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "erro") %> encontrado(s)</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="label">
    <%= form.label "Nome", :class => "label-text" %>
    <%= form.text_field :name, :class => "input-field", :placeholder => "Obrigatorio"  %>
  </div>

  <div class="label">
    <%= form.label "Email", :class => "label-text" %>
    <%= form.text_field :email, :class => "input-field", :placeholder => "Obrigatorio"  %>
  </div>

  <div class="label">
    <%= form.label "Senha", :class => "label-text" %>
    <%= form.password_field :password, :class => "input-field", :placeholder => "Obrigatorio"  %>
  </div>

  <div class="label">
    <%= form.label "Confirmação de senha", :class => "label-text" %>
    <%= form.password_field :password_confirmation, :class => "input-field", :placeholder => "Obrigatorio"  %>
  </div>

  <div class="submit-label">
    <button class="submit-button">
      <i class="material-icons">
        done
      </i>
    </button>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: "shared/nav" %>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<%= render partial: "/shared/nav" %>


<p id="notice"><%= notice %></p>
<% if current_user && current_user.email == "admin@doaki.com"%>
  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', signup_path %>
<% else %>
  <%= render partial: "shared/blocked-page"%>
<% end %>

app/views/users/new.html.erb
<%= render partial: "shared/nav" %>
  <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= render partial: "/shared/nav" %>

<div class="user-show-container">
	<i class="material-icons icon">person_pin</i>
	<span class="user-show-title">Suas informações</span>
	<div class="information">
		<div><strong>Nome:</strong> <%= @user.name %></div>
		<div><strong>Email:</strong> <%= @user.email %></div>
	</div>
	<%= link_to 'Editar', edit_user_path(@user), class: "edit-user-button" %>
	<div id="separate-infos">&nbsp</div>	
	<span class="user-show-title margin-bottom-title">Suas doações</span>
</div>
<div class="user-donations">
	<% if current_user %>
		<% if current_user.donations.length == 0 %>
			<p class="no-donations-user">Não há doações feitas por você...</p>
		<% else %>
			<% current_user.donations.each do |donation| %>
				<div class="user-donation-container">
					<%= link_to donation_path(donation), :class => "donation-link" do %>
						<div class="user-donation">
							<div class="us-don-image-container">
						        <% if donation.images.attached? %>
						            <%= image_tag(donation.images[0], :class => "us-don-image") %>
						        <% else %>
						          <%= image_tag("picture", :class => "us-don-no-image") %>
						        <% end%> 
				    	  	</div>
				    	    <div class="us-don-text">
						        <h1 class = "us-don-title"><%= donation.title %></h2>
						        <div class="us-don-description">
						            <p class="us-don-description-paragraph"><%= donation.description %></p>
						        </div>
				        	</div>
						</div>
					<% end %>
		        	<div class="us-don-options">
		        		<%= link_to 'Editar', edit_donation_path(donation), class: "us-don-button button-edit" %>
						    <%= link_to 'Deletar', donation, method: :delete, data: { confirm: 'Tem certeza?'}, class: "us-don-button button-delete" %>
		        	</div>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>