config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :donations

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :comments
end

app/views/shared/_blocked-page.html.erb
  <div class="block-page-container">
    <i class="material-icons block-page-icon">block</i>
    <h1 class="block-page-message">Ops! <br>
     Você não tem acesso a essa página! </h1>
  </div>

app/views/shared/_nav.html.erb
<head>
<style>
@import url('https://fonts.googleapis.com/css?family=ZCOOL+KuaiLe');
@import url('https://fonts.googleapis.com/css?family=Montserrat');
</style>

</head>
<nav>
    <div class="nav-logo">
        <%= link_to "Doaki", root_path, :class => "logo" %>
    </div>
        <%= form_tag donations_path, :method => 'get', :class => "nav-search-bar" do %>
            <%= text_field_tag :search, params[:search], :class => "nav-search", :placeholder => "O que está procurando?" %>
            <%= button_tag(type: "submit", class:"nav-button-search") do %>
                <i class="material-icons search-icon">search</i>
            <% end %>
        <% end %>

    <ul class="nav-buttons-list">
        <% if current_user %>
            <%= link_to 'DOAR',  new_donation_path, :class => "nav-buttons" %>
            <%= link_to 'Sair', logout_path, method: :delete, :class => "nav-buttons" %>
            <span class="profile-span">
                <%= link_to user_path(current_user.id), :class => "profile-hyperlink" do %>
                    <i class="material-icons md-36 profile-icon">account_circle</i>
                <% end %>
            </span>
        <% else %>
            <%= link_to "Cadastrar", signup_path, :class => "nav-buttons sing-up" %>
            <%= link_to "Login", login_path, :class => "nav-buttons sing-up" %>
        <% end %>
    </ul>
</nav>